spring.application.name=EC-Config_Server

server.port=6666

#External Application properties File
spring.cloud.config.server.git.uri=https://github.com/satyamk-dev/OnlineBookHouse_Config_Server.git

spring.cloud.config.server.git.default-label=master

spring.cloud.config.server.git.skip-ssl-validation=false

spring.cloud.config.server.git.clone-on-start=false

spring.cloud.config.server.bootstrap=false

management.endpoints.web.exposure.include=*